# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bdc3c51615c47e7faa0ce580a74b74687597d7ce644655d1667dc5b9c8b739ec6b082e4003dcf3451f144cff2e48c8e557091ed2c31482f842845dc093680420

test:
  secret_key_base: b7d6951ad882ff8df2d2944ea1c111b1684ea7741074d7be7158c2016b835f833f2fcb38bd1a967d667dbd0a53880fcd7fe246a7a33ee5a2848260b5c0bd07cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
